"""Change fields in book

Revision ID: d9f6e871f7bf
Revises: f22e5f6a4535
Create Date: 2024-07-08 21:27:00.104859

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d9f6e871f7bf"
down_revision = "f22e5f6a4535"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("books", schema=None) as batch_op:
        batch_op.alter_column(
            "author", existing_type=sa.VARCHAR(length=255), nullable=True
        )
        batch_op.alter_column(
            "isbn", existing_type=sa.VARCHAR(length=20), nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("books", schema=None) as batch_op:
        batch_op.alter_column(
            "isbn", existing_type=sa.VARCHAR(length=20), nullable=False
        )
        batch_op.alter_column(
            "author", existing_type=sa.VARCHAR(length=255), nullable=False
        )

    # ### end Alembic commands ###
